// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_action.proto

#ifndef PROTOBUF_INCLUDED_generic_5faction_2eproto
#define PROTOBUF_INCLUDED_generic_5faction_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_generic_5faction_2eproto 

namespace protobuf_generic_5faction_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_generic_5faction_2eproto
namespace CoreX {
namespace rpc {
class GenericCommand;
class GenericCommandDefaultTypeInternal;
extern GenericCommandDefaultTypeInternal _GenericCommand_default_instance_;
class GenericResponse;
class GenericResponseDefaultTypeInternal;
extern GenericResponseDefaultTypeInternal _GenericResponse_default_instance_;
}  // namespace rpc
}  // namespace CoreX
namespace google {
namespace protobuf {
template<> ::CoreX::rpc::GenericCommand* Arena::CreateMaybeMessage<::CoreX::rpc::GenericCommand>(Arena*);
template<> ::CoreX::rpc::GenericResponse* Arena::CreateMaybeMessage<::CoreX::rpc::GenericResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace CoreX {
namespace rpc {

// ===================================================================

class GenericCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.GenericCommand) */ {
 public:
  GenericCommand();
  virtual ~GenericCommand();

  GenericCommand(const GenericCommand& from);

  inline GenericCommand& operator=(const GenericCommand& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenericCommand(GenericCommand&& from) noexcept
    : GenericCommand() {
    *this = ::std::move(from);
  }

  inline GenericCommand& operator=(GenericCommand&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GenericCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenericCommand* internal_default_instance() {
    return reinterpret_cast<const GenericCommand*>(
               &_GenericCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GenericCommand* other);
  friend void swap(GenericCommand& a, GenericCommand& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenericCommand* New() const final {
    return CreateMaybeMessage<GenericCommand>(NULL);
  }

  GenericCommand* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GenericCommand>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GenericCommand& from);
  void MergeFrom(const GenericCommand& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenericCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string action = 1;
  void clear_action();
  static const int kActionFieldNumber = 1;
  const ::std::string& action() const;
  void set_action(const ::std::string& value);
  #if LANG_CXX11
  void set_action(::std::string&& value);
  #endif
  void set_action(const char* value);
  void set_action(const char* value, size_t size);
  ::std::string* mutable_action();
  ::std::string* release_action();
  void set_allocated_action(::std::string* action);

  // bytes params = 2;
  void clear_params();
  static const int kParamsFieldNumber = 2;
  const ::std::string& params() const;
  void set_params(const ::std::string& value);
  #if LANG_CXX11
  void set_params(::std::string&& value);
  #endif
  void set_params(const char* value);
  void set_params(const void* value, size_t size);
  ::std::string* mutable_params();
  ::std::string* release_params();
  void set_allocated_params(::std::string* params);

  // @@protoc_insertion_point(class_scope:CoreX.rpc.GenericCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr action_;
  ::google::protobuf::internal::ArenaStringPtr params_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_generic_5faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GenericResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.GenericResponse) */ {
 public:
  GenericResponse();
  virtual ~GenericResponse();

  GenericResponse(const GenericResponse& from);

  inline GenericResponse& operator=(const GenericResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenericResponse(GenericResponse&& from) noexcept
    : GenericResponse() {
    *this = ::std::move(from);
  }

  inline GenericResponse& operator=(GenericResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GenericResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenericResponse* internal_default_instance() {
    return reinterpret_cast<const GenericResponse*>(
               &_GenericResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GenericResponse* other);
  friend void swap(GenericResponse& a, GenericResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenericResponse* New() const final {
    return CreateMaybeMessage<GenericResponse>(NULL);
  }

  GenericResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GenericResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GenericResponse& from);
  void MergeFrom(const GenericResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GenericResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // bytes data = 3;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // string error_msg = 4;
  void clear_error_msg();
  static const int kErrorMsgFieldNumber = 4;
  const ::std::string& error_msg() const;
  void set_error_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_error_msg(::std::string&& value);
  #endif
  void set_error_msg(const char* value);
  void set_error_msg(const char* value, size_t size);
  ::std::string* mutable_error_msg();
  ::std::string* release_error_msg();
  void set_allocated_error_msg(::std::string* error_msg);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:CoreX.rpc.GenericResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::internal::ArenaStringPtr error_msg_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_generic_5faction_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GenericCommand

// string action = 1;
inline void GenericCommand::clear_action() {
  action_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericCommand::action() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.GenericCommand.action)
  return action_.GetNoArena();
}
inline void GenericCommand::set_action(const ::std::string& value) {
  
  action_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.GenericCommand.action)
}
#if LANG_CXX11
inline void GenericCommand::set_action(::std::string&& value) {
  
  action_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.GenericCommand.action)
}
#endif
inline void GenericCommand::set_action(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  action_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.GenericCommand.action)
}
inline void GenericCommand::set_action(const char* value, size_t size) {
  
  action_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.GenericCommand.action)
}
inline ::std::string* GenericCommand::mutable_action() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.GenericCommand.action)
  return action_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericCommand::release_action() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.GenericCommand.action)
  
  return action_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericCommand::set_allocated_action(::std::string* action) {
  if (action != NULL) {
    
  } else {
    
  }
  action_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), action);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.GenericCommand.action)
}

// bytes params = 2;
inline void GenericCommand::clear_params() {
  params_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericCommand::params() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.GenericCommand.params)
  return params_.GetNoArena();
}
inline void GenericCommand::set_params(const ::std::string& value) {
  
  params_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.GenericCommand.params)
}
#if LANG_CXX11
inline void GenericCommand::set_params(::std::string&& value) {
  
  params_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.GenericCommand.params)
}
#endif
inline void GenericCommand::set_params(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  params_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.GenericCommand.params)
}
inline void GenericCommand::set_params(const void* value, size_t size) {
  
  params_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.GenericCommand.params)
}
inline ::std::string* GenericCommand::mutable_params() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.GenericCommand.params)
  return params_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericCommand::release_params() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.GenericCommand.params)
  
  return params_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericCommand::set_allocated_params(::std::string* params) {
  if (params != NULL) {
    
  } else {
    
  }
  params_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), params);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.GenericCommand.params)
}

// -------------------------------------------------------------------

// GenericResponse

// bool success = 1;
inline void GenericResponse::clear_success() {
  success_ = false;
}
inline bool GenericResponse::success() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.GenericResponse.success)
  return success_;
}
inline void GenericResponse::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.GenericResponse.success)
}

// string message = 2;
inline void GenericResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericResponse::message() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.GenericResponse.message)
  return message_.GetNoArena();
}
inline void GenericResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.GenericResponse.message)
}
#if LANG_CXX11
inline void GenericResponse::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.GenericResponse.message)
}
#endif
inline void GenericResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.GenericResponse.message)
}
inline void GenericResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.GenericResponse.message)
}
inline ::std::string* GenericResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.GenericResponse.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericResponse::release_message() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.GenericResponse.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.GenericResponse.message)
}

// bytes data = 3;
inline void GenericResponse::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericResponse::data() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.GenericResponse.data)
  return data_.GetNoArena();
}
inline void GenericResponse::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.GenericResponse.data)
}
#if LANG_CXX11
inline void GenericResponse::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.GenericResponse.data)
}
#endif
inline void GenericResponse::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.GenericResponse.data)
}
inline void GenericResponse::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.GenericResponse.data)
}
inline ::std::string* GenericResponse::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.GenericResponse.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericResponse::release_data() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.GenericResponse.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericResponse::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.GenericResponse.data)
}

// string error_msg = 4;
inline void GenericResponse::clear_error_msg() {
  error_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericResponse::error_msg() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.GenericResponse.error_msg)
  return error_msg_.GetNoArena();
}
inline void GenericResponse::set_error_msg(const ::std::string& value) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.GenericResponse.error_msg)
}
#if LANG_CXX11
inline void GenericResponse::set_error_msg(::std::string&& value) {
  
  error_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.GenericResponse.error_msg)
}
#endif
inline void GenericResponse::set_error_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.GenericResponse.error_msg)
}
inline void GenericResponse::set_error_msg(const char* value, size_t size) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.GenericResponse.error_msg)
}
inline ::std::string* GenericResponse::mutable_error_msg() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.GenericResponse.error_msg)
  return error_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericResponse::release_error_msg() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.GenericResponse.error_msg)
  
  return error_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericResponse::set_allocated_error_msg(::std::string* error_msg) {
  if (error_msg != NULL) {
    
  } else {
    
  }
  error_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_msg);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.GenericResponse.error_msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace CoreX

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_generic_5faction_2eproto
