// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_service.proto

#ifndef PROTOBUF_INCLUDED_robot_5fservice_2eproto
#define PROTOBUF_INCLUDED_robot_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_robot_5fservice_2eproto 

namespace protobuf_robot_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_robot_5fservice_2eproto
namespace CoreX {
namespace rpc {
class ControlResponse;
class ControlResponseDefaultTypeInternal;
extern ControlResponseDefaultTypeInternal _ControlResponse_default_instance_;
class OdometryRequest;
class OdometryRequestDefaultTypeInternal;
extern OdometryRequestDefaultTypeInternal _OdometryRequest_default_instance_;
class OdometryResponse;
class OdometryResponseDefaultTypeInternal;
extern OdometryResponseDefaultTypeInternal _OdometryResponse_default_instance_;
class StatusRequest;
class StatusRequestDefaultTypeInternal;
extern StatusRequestDefaultTypeInternal _StatusRequest_default_instance_;
class StatusResponse;
class StatusResponseDefaultTypeInternal;
extern StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;
class VelocityCommand;
class VelocityCommandDefaultTypeInternal;
extern VelocityCommandDefaultTypeInternal _VelocityCommand_default_instance_;
}  // namespace rpc
}  // namespace CoreX
namespace google {
namespace protobuf {
template<> ::CoreX::rpc::ControlResponse* Arena::CreateMaybeMessage<::CoreX::rpc::ControlResponse>(Arena*);
template<> ::CoreX::rpc::OdometryRequest* Arena::CreateMaybeMessage<::CoreX::rpc::OdometryRequest>(Arena*);
template<> ::CoreX::rpc::OdometryResponse* Arena::CreateMaybeMessage<::CoreX::rpc::OdometryResponse>(Arena*);
template<> ::CoreX::rpc::StatusRequest* Arena::CreateMaybeMessage<::CoreX::rpc::StatusRequest>(Arena*);
template<> ::CoreX::rpc::StatusResponse* Arena::CreateMaybeMessage<::CoreX::rpc::StatusResponse>(Arena*);
template<> ::CoreX::rpc::VelocityCommand* Arena::CreateMaybeMessage<::CoreX::rpc::VelocityCommand>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace CoreX {
namespace rpc {

// ===================================================================

class OdometryRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.OdometryRequest) */ {
 public:
  OdometryRequest();
  virtual ~OdometryRequest();

  OdometryRequest(const OdometryRequest& from);

  inline OdometryRequest& operator=(const OdometryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OdometryRequest(OdometryRequest&& from) noexcept
    : OdometryRequest() {
    *this = ::std::move(from);
  }

  inline OdometryRequest& operator=(OdometryRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OdometryRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OdometryRequest* internal_default_instance() {
    return reinterpret_cast<const OdometryRequest*>(
               &_OdometryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(OdometryRequest* other);
  friend void swap(OdometryRequest& a, OdometryRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OdometryRequest* New() const final {
    return CreateMaybeMessage<OdometryRequest>(NULL);
  }

  OdometryRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OdometryRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OdometryRequest& from);
  void MergeFrom(const OdometryRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OdometryRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CoreX.rpc.OdometryRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OdometryResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.OdometryResponse) */ {
 public:
  OdometryResponse();
  virtual ~OdometryResponse();

  OdometryResponse(const OdometryResponse& from);

  inline OdometryResponse& operator=(const OdometryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OdometryResponse(OdometryResponse&& from) noexcept
    : OdometryResponse() {
    *this = ::std::move(from);
  }

  inline OdometryResponse& operator=(OdometryResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const OdometryResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OdometryResponse* internal_default_instance() {
    return reinterpret_cast<const OdometryResponse*>(
               &_OdometryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(OdometryResponse* other);
  friend void swap(OdometryResponse& a, OdometryResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OdometryResponse* New() const final {
    return CreateMaybeMessage<OdometryResponse>(NULL);
  }

  OdometryResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OdometryResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OdometryResponse& from);
  void MergeFrom(const OdometryResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OdometryResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double pos_x = 1;
  void clear_pos_x();
  static const int kPosXFieldNumber = 1;
  double pos_x() const;
  void set_pos_x(double value);

  // double pos_y = 2;
  void clear_pos_y();
  static const int kPosYFieldNumber = 2;
  double pos_y() const;
  void set_pos_y(double value);

  // double pos_z = 3;
  void clear_pos_z();
  static const int kPosZFieldNumber = 3;
  double pos_z() const;
  void set_pos_z(double value);

  // double orient_x = 4;
  void clear_orient_x();
  static const int kOrientXFieldNumber = 4;
  double orient_x() const;
  void set_orient_x(double value);

  // double orient_y = 5;
  void clear_orient_y();
  static const int kOrientYFieldNumber = 5;
  double orient_y() const;
  void set_orient_y(double value);

  // double orient_z = 6;
  void clear_orient_z();
  static const int kOrientZFieldNumber = 6;
  double orient_z() const;
  void set_orient_z(double value);

  // double orient_w = 7;
  void clear_orient_w();
  static const int kOrientWFieldNumber = 7;
  double orient_w() const;
  void set_orient_w(double value);

  // double vel_x = 8;
  void clear_vel_x();
  static const int kVelXFieldNumber = 8;
  double vel_x() const;
  void set_vel_x(double value);

  // double vel_y = 9;
  void clear_vel_y();
  static const int kVelYFieldNumber = 9;
  double vel_y() const;
  void set_vel_y(double value);

  // double vel_z = 10;
  void clear_vel_z();
  static const int kVelZFieldNumber = 10;
  double vel_z() const;
  void set_vel_z(double value);

  // double ang_x = 11;
  void clear_ang_x();
  static const int kAngXFieldNumber = 11;
  double ang_x() const;
  void set_ang_x(double value);

  // double ang_y = 12;
  void clear_ang_y();
  static const int kAngYFieldNumber = 12;
  double ang_y() const;
  void set_ang_y(double value);

  // double ang_z = 13;
  void clear_ang_z();
  static const int kAngZFieldNumber = 13;
  double ang_z() const;
  void set_ang_z(double value);

  // uint64 timestamp = 14;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 14;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // bool success = 15;
  void clear_success();
  static const int kSuccessFieldNumber = 15;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:CoreX.rpc.OdometryResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double pos_x_;
  double pos_y_;
  double pos_z_;
  double orient_x_;
  double orient_y_;
  double orient_z_;
  double orient_w_;
  double vel_x_;
  double vel_y_;
  double vel_z_;
  double ang_x_;
  double ang_y_;
  double ang_z_;
  ::google::protobuf::uint64 timestamp_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StatusRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.StatusRequest) */ {
 public:
  StatusRequest();
  virtual ~StatusRequest();

  StatusRequest(const StatusRequest& from);

  inline StatusRequest& operator=(const StatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusRequest(StatusRequest&& from) noexcept
    : StatusRequest() {
    *this = ::std::move(from);
  }

  inline StatusRequest& operator=(StatusRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusRequest* internal_default_instance() {
    return reinterpret_cast<const StatusRequest*>(
               &_StatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(StatusRequest* other);
  friend void swap(StatusRequest& a, StatusRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusRequest* New() const final {
    return CreateMaybeMessage<StatusRequest>(NULL);
  }

  StatusRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatusRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatusRequest& from);
  void MergeFrom(const StatusRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CoreX.rpc.StatusRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StatusResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.StatusResponse) */ {
 public:
  StatusResponse();
  virtual ~StatusResponse();

  StatusResponse(const StatusResponse& from);

  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatusResponse(StatusResponse&& from) noexcept
    : StatusResponse() {
    *this = ::std::move(from);
  }

  inline StatusResponse& operator=(StatusResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatusResponse* internal_default_instance() {
    return reinterpret_cast<const StatusResponse*>(
               &_StatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(StatusResponse* other);
  friend void swap(StatusResponse& a, StatusResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatusResponse* New() const final {
    return CreateMaybeMessage<StatusResponse>(NULL);
  }

  StatusResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StatusResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StatusResponse& from);
  void MergeFrom(const StatusResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string status_msg = 5;
  void clear_status_msg();
  static const int kStatusMsgFieldNumber = 5;
  const ::std::string& status_msg() const;
  void set_status_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_status_msg(::std::string&& value);
  #endif
  void set_status_msg(const char* value);
  void set_status_msg(const char* value, size_t size);
  ::std::string* mutable_status_msg();
  ::std::string* release_status_msg();
  void set_allocated_status_msg(::std::string* status_msg);

  // double battery_v = 1;
  void clear_battery_v();
  static const int kBatteryVFieldNumber = 1;
  double battery_v() const;
  void set_battery_v(double value);

  // double battery_pct = 2;
  void clear_battery_pct();
  static const int kBatteryPctFieldNumber = 2;
  double battery_pct() const;
  void set_battery_pct(double value);

  // uint64 timestamp = 6;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 6;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // bool is_charging = 3;
  void clear_is_charging();
  static const int kIsChargingFieldNumber = 3;
  bool is_charging() const;
  void set_is_charging(bool value);

  // bool emergency_stop = 4;
  void clear_emergency_stop();
  static const int kEmergencyStopFieldNumber = 4;
  bool emergency_stop() const;
  void set_emergency_stop(bool value);

  // @@protoc_insertion_point(class_scope:CoreX.rpc.StatusResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr status_msg_;
  double battery_v_;
  double battery_pct_;
  ::google::protobuf::uint64 timestamp_;
  bool is_charging_;
  bool emergency_stop_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class VelocityCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.VelocityCommand) */ {
 public:
  VelocityCommand();
  virtual ~VelocityCommand();

  VelocityCommand(const VelocityCommand& from);

  inline VelocityCommand& operator=(const VelocityCommand& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VelocityCommand(VelocityCommand&& from) noexcept
    : VelocityCommand() {
    *this = ::std::move(from);
  }

  inline VelocityCommand& operator=(VelocityCommand&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VelocityCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VelocityCommand* internal_default_instance() {
    return reinterpret_cast<const VelocityCommand*>(
               &_VelocityCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(VelocityCommand* other);
  friend void swap(VelocityCommand& a, VelocityCommand& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VelocityCommand* New() const final {
    return CreateMaybeMessage<VelocityCommand>(NULL);
  }

  VelocityCommand* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VelocityCommand>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VelocityCommand& from);
  void MergeFrom(const VelocityCommand& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VelocityCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double linear_x = 1;
  void clear_linear_x();
  static const int kLinearXFieldNumber = 1;
  double linear_x() const;
  void set_linear_x(double value);

  // double linear_y = 2;
  void clear_linear_y();
  static const int kLinearYFieldNumber = 2;
  double linear_y() const;
  void set_linear_y(double value);

  // double linear_z = 3;
  void clear_linear_z();
  static const int kLinearZFieldNumber = 3;
  double linear_z() const;
  void set_linear_z(double value);

  // double angular_x = 4;
  void clear_angular_x();
  static const int kAngularXFieldNumber = 4;
  double angular_x() const;
  void set_angular_x(double value);

  // double angular_y = 5;
  void clear_angular_y();
  static const int kAngularYFieldNumber = 5;
  double angular_y() const;
  void set_angular_y(double value);

  // double angular_z = 6;
  void clear_angular_z();
  static const int kAngularZFieldNumber = 6;
  double angular_z() const;
  void set_angular_z(double value);

  // @@protoc_insertion_point(class_scope:CoreX.rpc.VelocityCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double linear_x_;
  double linear_y_;
  double linear_z_;
  double angular_x_;
  double angular_y_;
  double angular_z_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ControlResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CoreX.rpc.ControlResponse) */ {
 public:
  ControlResponse();
  virtual ~ControlResponse();

  ControlResponse(const ControlResponse& from);

  inline ControlResponse& operator=(const ControlResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ControlResponse(ControlResponse&& from) noexcept
    : ControlResponse() {
    *this = ::std::move(from);
  }

  inline ControlResponse& operator=(ControlResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ControlResponse* internal_default_instance() {
    return reinterpret_cast<const ControlResponse*>(
               &_ControlResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ControlResponse* other);
  friend void swap(ControlResponse& a, ControlResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ControlResponse* New() const final {
    return CreateMaybeMessage<ControlResponse>(NULL);
  }

  ControlResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ControlResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ControlResponse& from);
  void MergeFrom(const ControlResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error_msg = 2;
  void clear_error_msg();
  static const int kErrorMsgFieldNumber = 2;
  const ::std::string& error_msg() const;
  void set_error_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_error_msg(::std::string&& value);
  #endif
  void set_error_msg(const char* value);
  void set_error_msg(const char* value, size_t size);
  ::std::string* mutable_error_msg();
  ::std::string* release_error_msg();
  void set_allocated_error_msg(::std::string* error_msg);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:CoreX.rpc.ControlResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_msg_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_robot_5fservice_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OdometryRequest

// -------------------------------------------------------------------

// OdometryResponse

// double pos_x = 1;
inline void OdometryResponse::clear_pos_x() {
  pos_x_ = 0;
}
inline double OdometryResponse::pos_x() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.pos_x)
  return pos_x_;
}
inline void OdometryResponse::set_pos_x(double value) {
  
  pos_x_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.pos_x)
}

// double pos_y = 2;
inline void OdometryResponse::clear_pos_y() {
  pos_y_ = 0;
}
inline double OdometryResponse::pos_y() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.pos_y)
  return pos_y_;
}
inline void OdometryResponse::set_pos_y(double value) {
  
  pos_y_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.pos_y)
}

// double pos_z = 3;
inline void OdometryResponse::clear_pos_z() {
  pos_z_ = 0;
}
inline double OdometryResponse::pos_z() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.pos_z)
  return pos_z_;
}
inline void OdometryResponse::set_pos_z(double value) {
  
  pos_z_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.pos_z)
}

// double orient_x = 4;
inline void OdometryResponse::clear_orient_x() {
  orient_x_ = 0;
}
inline double OdometryResponse::orient_x() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.orient_x)
  return orient_x_;
}
inline void OdometryResponse::set_orient_x(double value) {
  
  orient_x_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.orient_x)
}

// double orient_y = 5;
inline void OdometryResponse::clear_orient_y() {
  orient_y_ = 0;
}
inline double OdometryResponse::orient_y() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.orient_y)
  return orient_y_;
}
inline void OdometryResponse::set_orient_y(double value) {
  
  orient_y_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.orient_y)
}

// double orient_z = 6;
inline void OdometryResponse::clear_orient_z() {
  orient_z_ = 0;
}
inline double OdometryResponse::orient_z() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.orient_z)
  return orient_z_;
}
inline void OdometryResponse::set_orient_z(double value) {
  
  orient_z_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.orient_z)
}

// double orient_w = 7;
inline void OdometryResponse::clear_orient_w() {
  orient_w_ = 0;
}
inline double OdometryResponse::orient_w() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.orient_w)
  return orient_w_;
}
inline void OdometryResponse::set_orient_w(double value) {
  
  orient_w_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.orient_w)
}

// double vel_x = 8;
inline void OdometryResponse::clear_vel_x() {
  vel_x_ = 0;
}
inline double OdometryResponse::vel_x() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.vel_x)
  return vel_x_;
}
inline void OdometryResponse::set_vel_x(double value) {
  
  vel_x_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.vel_x)
}

// double vel_y = 9;
inline void OdometryResponse::clear_vel_y() {
  vel_y_ = 0;
}
inline double OdometryResponse::vel_y() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.vel_y)
  return vel_y_;
}
inline void OdometryResponse::set_vel_y(double value) {
  
  vel_y_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.vel_y)
}

// double vel_z = 10;
inline void OdometryResponse::clear_vel_z() {
  vel_z_ = 0;
}
inline double OdometryResponse::vel_z() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.vel_z)
  return vel_z_;
}
inline void OdometryResponse::set_vel_z(double value) {
  
  vel_z_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.vel_z)
}

// double ang_x = 11;
inline void OdometryResponse::clear_ang_x() {
  ang_x_ = 0;
}
inline double OdometryResponse::ang_x() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.ang_x)
  return ang_x_;
}
inline void OdometryResponse::set_ang_x(double value) {
  
  ang_x_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.ang_x)
}

// double ang_y = 12;
inline void OdometryResponse::clear_ang_y() {
  ang_y_ = 0;
}
inline double OdometryResponse::ang_y() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.ang_y)
  return ang_y_;
}
inline void OdometryResponse::set_ang_y(double value) {
  
  ang_y_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.ang_y)
}

// double ang_z = 13;
inline void OdometryResponse::clear_ang_z() {
  ang_z_ = 0;
}
inline double OdometryResponse::ang_z() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.ang_z)
  return ang_z_;
}
inline void OdometryResponse::set_ang_z(double value) {
  
  ang_z_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.ang_z)
}

// uint64 timestamp = 14;
inline void OdometryResponse::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OdometryResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.timestamp)
  return timestamp_;
}
inline void OdometryResponse::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.timestamp)
}

// bool success = 15;
inline void OdometryResponse::clear_success() {
  success_ = false;
}
inline bool OdometryResponse::success() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.OdometryResponse.success)
  return success_;
}
inline void OdometryResponse::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.OdometryResponse.success)
}

// -------------------------------------------------------------------

// StatusRequest

// -------------------------------------------------------------------

// StatusResponse

// double battery_v = 1;
inline void StatusResponse::clear_battery_v() {
  battery_v_ = 0;
}
inline double StatusResponse::battery_v() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.StatusResponse.battery_v)
  return battery_v_;
}
inline void StatusResponse::set_battery_v(double value) {
  
  battery_v_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.StatusResponse.battery_v)
}

// double battery_pct = 2;
inline void StatusResponse::clear_battery_pct() {
  battery_pct_ = 0;
}
inline double StatusResponse::battery_pct() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.StatusResponse.battery_pct)
  return battery_pct_;
}
inline void StatusResponse::set_battery_pct(double value) {
  
  battery_pct_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.StatusResponse.battery_pct)
}

// bool is_charging = 3;
inline void StatusResponse::clear_is_charging() {
  is_charging_ = false;
}
inline bool StatusResponse::is_charging() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.StatusResponse.is_charging)
  return is_charging_;
}
inline void StatusResponse::set_is_charging(bool value) {
  
  is_charging_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.StatusResponse.is_charging)
}

// bool emergency_stop = 4;
inline void StatusResponse::clear_emergency_stop() {
  emergency_stop_ = false;
}
inline bool StatusResponse::emergency_stop() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.StatusResponse.emergency_stop)
  return emergency_stop_;
}
inline void StatusResponse::set_emergency_stop(bool value) {
  
  emergency_stop_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.StatusResponse.emergency_stop)
}

// string status_msg = 5;
inline void StatusResponse::clear_status_msg() {
  status_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& StatusResponse::status_msg() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.StatusResponse.status_msg)
  return status_msg_.GetNoArena();
}
inline void StatusResponse::set_status_msg(const ::std::string& value) {
  
  status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.StatusResponse.status_msg)
}
#if LANG_CXX11
inline void StatusResponse::set_status_msg(::std::string&& value) {
  
  status_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.StatusResponse.status_msg)
}
#endif
inline void StatusResponse::set_status_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.StatusResponse.status_msg)
}
inline void StatusResponse::set_status_msg(const char* value, size_t size) {
  
  status_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.StatusResponse.status_msg)
}
inline ::std::string* StatusResponse::mutable_status_msg() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.StatusResponse.status_msg)
  return status_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StatusResponse::release_status_msg() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.StatusResponse.status_msg)
  
  return status_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StatusResponse::set_allocated_status_msg(::std::string* status_msg) {
  if (status_msg != NULL) {
    
  } else {
    
  }
  status_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status_msg);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.StatusResponse.status_msg)
}

// uint64 timestamp = 6;
inline void StatusResponse::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 StatusResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.StatusResponse.timestamp)
  return timestamp_;
}
inline void StatusResponse::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.StatusResponse.timestamp)
}

// -------------------------------------------------------------------

// VelocityCommand

// double linear_x = 1;
inline void VelocityCommand::clear_linear_x() {
  linear_x_ = 0;
}
inline double VelocityCommand::linear_x() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.VelocityCommand.linear_x)
  return linear_x_;
}
inline void VelocityCommand::set_linear_x(double value) {
  
  linear_x_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.VelocityCommand.linear_x)
}

// double linear_y = 2;
inline void VelocityCommand::clear_linear_y() {
  linear_y_ = 0;
}
inline double VelocityCommand::linear_y() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.VelocityCommand.linear_y)
  return linear_y_;
}
inline void VelocityCommand::set_linear_y(double value) {
  
  linear_y_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.VelocityCommand.linear_y)
}

// double linear_z = 3;
inline void VelocityCommand::clear_linear_z() {
  linear_z_ = 0;
}
inline double VelocityCommand::linear_z() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.VelocityCommand.linear_z)
  return linear_z_;
}
inline void VelocityCommand::set_linear_z(double value) {
  
  linear_z_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.VelocityCommand.linear_z)
}

// double angular_x = 4;
inline void VelocityCommand::clear_angular_x() {
  angular_x_ = 0;
}
inline double VelocityCommand::angular_x() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.VelocityCommand.angular_x)
  return angular_x_;
}
inline void VelocityCommand::set_angular_x(double value) {
  
  angular_x_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.VelocityCommand.angular_x)
}

// double angular_y = 5;
inline void VelocityCommand::clear_angular_y() {
  angular_y_ = 0;
}
inline double VelocityCommand::angular_y() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.VelocityCommand.angular_y)
  return angular_y_;
}
inline void VelocityCommand::set_angular_y(double value) {
  
  angular_y_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.VelocityCommand.angular_y)
}

// double angular_z = 6;
inline void VelocityCommand::clear_angular_z() {
  angular_z_ = 0;
}
inline double VelocityCommand::angular_z() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.VelocityCommand.angular_z)
  return angular_z_;
}
inline void VelocityCommand::set_angular_z(double value) {
  
  angular_z_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.VelocityCommand.angular_z)
}

// -------------------------------------------------------------------

// ControlResponse

// bool success = 1;
inline void ControlResponse::clear_success() {
  success_ = false;
}
inline bool ControlResponse::success() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.ControlResponse.success)
  return success_;
}
inline void ControlResponse::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:CoreX.rpc.ControlResponse.success)
}

// string error_msg = 2;
inline void ControlResponse::clear_error_msg() {
  error_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ControlResponse::error_msg() const {
  // @@protoc_insertion_point(field_get:CoreX.rpc.ControlResponse.error_msg)
  return error_msg_.GetNoArena();
}
inline void ControlResponse::set_error_msg(const ::std::string& value) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CoreX.rpc.ControlResponse.error_msg)
}
#if LANG_CXX11
inline void ControlResponse::set_error_msg(::std::string&& value) {
  
  error_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CoreX.rpc.ControlResponse.error_msg)
}
#endif
inline void ControlResponse::set_error_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CoreX.rpc.ControlResponse.error_msg)
}
inline void ControlResponse::set_error_msg(const char* value, size_t size) {
  
  error_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CoreX.rpc.ControlResponse.error_msg)
}
inline ::std::string* ControlResponse::mutable_error_msg() {
  
  // @@protoc_insertion_point(field_mutable:CoreX.rpc.ControlResponse.error_msg)
  return error_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ControlResponse::release_error_msg() {
  // @@protoc_insertion_point(field_release:CoreX.rpc.ControlResponse.error_msg)
  
  return error_msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ControlResponse::set_allocated_error_msg(::std::string* error_msg) {
  if (error_msg != NULL) {
    
  } else {
    
  }
  error_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_msg);
  // @@protoc_insertion_point(field_set_allocated:CoreX.rpc.ControlResponse.error_msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace CoreX

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_robot_5fservice_2eproto
