// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_service.proto

#include "robot_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace CoreX {
namespace rpc {
class OdometryRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OdometryRequest>
      _instance;
} _OdometryRequest_default_instance_;
class OdometryResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OdometryResponse>
      _instance;
} _OdometryResponse_default_instance_;
class StatusRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StatusRequest>
      _instance;
} _StatusRequest_default_instance_;
class StatusResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StatusResponse>
      _instance;
} _StatusResponse_default_instance_;
class VelocityCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VelocityCommand>
      _instance;
} _VelocityCommand_default_instance_;
class ControlResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ControlResponse>
      _instance;
} _ControlResponse_default_instance_;
}  // namespace rpc
}  // namespace CoreX
namespace protobuf_robot_5fservice_2eproto {
static void InitDefaultsOdometryRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CoreX::rpc::_OdometryRequest_default_instance_;
    new (ptr) ::CoreX::rpc::OdometryRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CoreX::rpc::OdometryRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_OdometryRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsOdometryRequest}, {}};

static void InitDefaultsOdometryResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CoreX::rpc::_OdometryResponse_default_instance_;
    new (ptr) ::CoreX::rpc::OdometryResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CoreX::rpc::OdometryResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_OdometryResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsOdometryResponse}, {}};

static void InitDefaultsStatusRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CoreX::rpc::_StatusRequest_default_instance_;
    new (ptr) ::CoreX::rpc::StatusRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CoreX::rpc::StatusRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StatusRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStatusRequest}, {}};

static void InitDefaultsStatusResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CoreX::rpc::_StatusResponse_default_instance_;
    new (ptr) ::CoreX::rpc::StatusResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CoreX::rpc::StatusResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StatusResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStatusResponse}, {}};

static void InitDefaultsVelocityCommand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CoreX::rpc::_VelocityCommand_default_instance_;
    new (ptr) ::CoreX::rpc::VelocityCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CoreX::rpc::VelocityCommand::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VelocityCommand =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVelocityCommand}, {}};

static void InitDefaultsControlResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CoreX::rpc::_ControlResponse_default_instance_;
    new (ptr) ::CoreX::rpc::ControlResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CoreX::rpc::ControlResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ControlResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsControlResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_OdometryRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_OdometryResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StatusRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StatusResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_VelocityCommand.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ControlResponse.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, pos_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, pos_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, pos_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, orient_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, orient_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, orient_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, orient_w_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, vel_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, vel_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, vel_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, ang_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, ang_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, ang_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::OdometryResponse, success_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, battery_v_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, battery_pct_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, is_charging_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, emergency_stop_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, status_msg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::StatusResponse, timestamp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, linear_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, linear_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, linear_z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, angular_x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, angular_y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::VelocityCommand, angular_z_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::ControlResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::ControlResponse, success_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CoreX::rpc::ControlResponse, error_msg_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::CoreX::rpc::OdometryRequest)},
  { 5, -1, sizeof(::CoreX::rpc::OdometryResponse)},
  { 25, -1, sizeof(::CoreX::rpc::StatusRequest)},
  { 30, -1, sizeof(::CoreX::rpc::StatusResponse)},
  { 41, -1, sizeof(::CoreX::rpc::VelocityCommand)},
  { 52, -1, sizeof(::CoreX::rpc::ControlResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::CoreX::rpc::_OdometryRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::CoreX::rpc::_OdometryResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::CoreX::rpc::_StatusRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::CoreX::rpc::_StatusResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::CoreX::rpc::_VelocityCommand_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::CoreX::rpc::_ControlResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "robot_service.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023robot_service.proto\022\tCoreX.rpc\"\021\n\017Odom"
      "etryRequest\"\205\002\n\020OdometryResponse\022\r\n\005pos_"
      "x\030\001 \001(\001\022\r\n\005pos_y\030\002 \001(\001\022\r\n\005pos_z\030\003 \001(\001\022\020\n"
      "\010orient_x\030\004 \001(\001\022\020\n\010orient_y\030\005 \001(\001\022\020\n\010ori"
      "ent_z\030\006 \001(\001\022\020\n\010orient_w\030\007 \001(\001\022\r\n\005vel_x\030\010"
      " \001(\001\022\r\n\005vel_y\030\t \001(\001\022\r\n\005vel_z\030\n \001(\001\022\r\n\005an"
      "g_x\030\013 \001(\001\022\r\n\005ang_y\030\014 \001(\001\022\r\n\005ang_z\030\r \001(\001\022"
      "\021\n\ttimestamp\030\016 \001(\004\022\017\n\007success\030\017 \001(\010\"\017\n\rS"
      "tatusRequest\"\214\001\n\016StatusResponse\022\021\n\tbatte"
      "ry_v\030\001 \001(\001\022\023\n\013battery_pct\030\002 \001(\001\022\023\n\013is_ch"
      "arging\030\003 \001(\010\022\026\n\016emergency_stop\030\004 \001(\010\022\022\n\n"
      "status_msg\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\004\"\200\001\n\017"
      "VelocityCommand\022\020\n\010linear_x\030\001 \001(\001\022\020\n\010lin"
      "ear_y\030\002 \001(\001\022\020\n\010linear_z\030\003 \001(\001\022\021\n\tangular"
      "_x\030\004 \001(\001\022\021\n\tangular_y\030\005 \001(\001\022\021\n\tangular_z"
      "\030\006 \001(\001\"5\n\017ControlResponse\022\017\n\007success\030\001 \001"
      "(\010\022\021\n\terror_msg\030\002 \001(\t2\232\001\n\016RobotTelemetry"
      "\022F\n\013GetOdometry\022\032.CoreX.rpc.OdometryRequ"
      "est\032\033.CoreX.rpc.OdometryResponse\022@\n\tGetS"
      "tatus\022\030.CoreX.rpc.StatusRequest\032\031.CoreX."
      "rpc.StatusResponse2\226\001\n\rMotionControl\022E\n\013"
      "SetVelocity\022\032.CoreX.rpc.VelocityCommand\032"
      "\032.CoreX.rpc.ControlResponse\022>\n\004Stop\022\032.Co"
      "reX.rpc.VelocityCommand\032\032.CoreX.rpc.Cont"
      "rolResponseb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 979);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "robot_service.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_robot_5fservice_2eproto
namespace CoreX {
namespace rpc {

// ===================================================================

void OdometryRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OdometryRequest::OdometryRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_robot_5fservice_2eproto::scc_info_OdometryRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CoreX.rpc.OdometryRequest)
}
OdometryRequest::OdometryRequest(const OdometryRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CoreX.rpc.OdometryRequest)
}

void OdometryRequest::SharedCtor() {
}

OdometryRequest::~OdometryRequest() {
  // @@protoc_insertion_point(destructor:CoreX.rpc.OdometryRequest)
  SharedDtor();
}

void OdometryRequest::SharedDtor() {
}

void OdometryRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* OdometryRequest::descriptor() {
  ::protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OdometryRequest& OdometryRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_robot_5fservice_2eproto::scc_info_OdometryRequest.base);
  return *internal_default_instance();
}


void OdometryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreX.rpc.OdometryRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool OdometryRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CoreX.rpc.OdometryRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:CoreX.rpc.OdometryRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CoreX.rpc.OdometryRequest)
  return false;
#undef DO_
}

void OdometryRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CoreX.rpc.OdometryRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CoreX.rpc.OdometryRequest)
}

::google::protobuf::uint8* OdometryRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CoreX.rpc.OdometryRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreX.rpc.OdometryRequest)
  return target;
}

size_t OdometryRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreX.rpc.OdometryRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OdometryRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CoreX.rpc.OdometryRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const OdometryRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OdometryRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CoreX.rpc.OdometryRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CoreX.rpc.OdometryRequest)
    MergeFrom(*source);
  }
}

void OdometryRequest::MergeFrom(const OdometryRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CoreX.rpc.OdometryRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void OdometryRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CoreX.rpc.OdometryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OdometryRequest::CopyFrom(const OdometryRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreX.rpc.OdometryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OdometryRequest::IsInitialized() const {
  return true;
}

void OdometryRequest::Swap(OdometryRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OdometryRequest::InternalSwap(OdometryRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata OdometryRequest::GetMetadata() const {
  protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void OdometryResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OdometryResponse::kPosXFieldNumber;
const int OdometryResponse::kPosYFieldNumber;
const int OdometryResponse::kPosZFieldNumber;
const int OdometryResponse::kOrientXFieldNumber;
const int OdometryResponse::kOrientYFieldNumber;
const int OdometryResponse::kOrientZFieldNumber;
const int OdometryResponse::kOrientWFieldNumber;
const int OdometryResponse::kVelXFieldNumber;
const int OdometryResponse::kVelYFieldNumber;
const int OdometryResponse::kVelZFieldNumber;
const int OdometryResponse::kAngXFieldNumber;
const int OdometryResponse::kAngYFieldNumber;
const int OdometryResponse::kAngZFieldNumber;
const int OdometryResponse::kTimestampFieldNumber;
const int OdometryResponse::kSuccessFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OdometryResponse::OdometryResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_robot_5fservice_2eproto::scc_info_OdometryResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CoreX.rpc.OdometryResponse)
}
OdometryResponse::OdometryResponse(const OdometryResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&pos_x_, &from.pos_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&success_) -
    reinterpret_cast<char*>(&pos_x_)) + sizeof(success_));
  // @@protoc_insertion_point(copy_constructor:CoreX.rpc.OdometryResponse)
}

void OdometryResponse::SharedCtor() {
  ::memset(&pos_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&success_) -
      reinterpret_cast<char*>(&pos_x_)) + sizeof(success_));
}

OdometryResponse::~OdometryResponse() {
  // @@protoc_insertion_point(destructor:CoreX.rpc.OdometryResponse)
  SharedDtor();
}

void OdometryResponse::SharedDtor() {
}

void OdometryResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* OdometryResponse::descriptor() {
  ::protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OdometryResponse& OdometryResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_robot_5fservice_2eproto::scc_info_OdometryResponse.base);
  return *internal_default_instance();
}


void OdometryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreX.rpc.OdometryResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&pos_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&success_) -
      reinterpret_cast<char*>(&pos_x_)) + sizeof(success_));
  _internal_metadata_.Clear();
}

bool OdometryResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CoreX.rpc.OdometryResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double pos_x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &pos_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double pos_y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &pos_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double pos_z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &pos_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double orient_x = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orient_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double orient_y = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orient_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double orient_z = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orient_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double orient_w = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &orient_w_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double vel_x = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vel_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double vel_y = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(73u /* 73 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vel_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double vel_z = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vel_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ang_x = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(89u /* 89 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ang_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ang_y = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(97u /* 97 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ang_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double ang_z = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(105u /* 105 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ang_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u /* 112 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool success = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(120u /* 120 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CoreX.rpc.OdometryResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CoreX.rpc.OdometryResponse)
  return false;
#undef DO_
}

void OdometryResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CoreX.rpc.OdometryResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double pos_x = 1;
  if (this->pos_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->pos_x(), output);
  }

  // double pos_y = 2;
  if (this->pos_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->pos_y(), output);
  }

  // double pos_z = 3;
  if (this->pos_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->pos_z(), output);
  }

  // double orient_x = 4;
  if (this->orient_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->orient_x(), output);
  }

  // double orient_y = 5;
  if (this->orient_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->orient_y(), output);
  }

  // double orient_z = 6;
  if (this->orient_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->orient_z(), output);
  }

  // double orient_w = 7;
  if (this->orient_w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->orient_w(), output);
  }

  // double vel_x = 8;
  if (this->vel_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->vel_x(), output);
  }

  // double vel_y = 9;
  if (this->vel_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->vel_y(), output);
  }

  // double vel_z = 10;
  if (this->vel_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->vel_z(), output);
  }

  // double ang_x = 11;
  if (this->ang_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->ang_x(), output);
  }

  // double ang_y = 12;
  if (this->ang_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->ang_y(), output);
  }

  // double ang_z = 13;
  if (this->ang_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->ang_z(), output);
  }

  // uint64 timestamp = 14;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(14, this->timestamp(), output);
  }

  // bool success = 15;
  if (this->success() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(15, this->success(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CoreX.rpc.OdometryResponse)
}

::google::protobuf::uint8* OdometryResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CoreX.rpc.OdometryResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double pos_x = 1;
  if (this->pos_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->pos_x(), target);
  }

  // double pos_y = 2;
  if (this->pos_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->pos_y(), target);
  }

  // double pos_z = 3;
  if (this->pos_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->pos_z(), target);
  }

  // double orient_x = 4;
  if (this->orient_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->orient_x(), target);
  }

  // double orient_y = 5;
  if (this->orient_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->orient_y(), target);
  }

  // double orient_z = 6;
  if (this->orient_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->orient_z(), target);
  }

  // double orient_w = 7;
  if (this->orient_w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->orient_w(), target);
  }

  // double vel_x = 8;
  if (this->vel_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->vel_x(), target);
  }

  // double vel_y = 9;
  if (this->vel_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->vel_y(), target);
  }

  // double vel_z = 10;
  if (this->vel_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->vel_z(), target);
  }

  // double ang_x = 11;
  if (this->ang_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->ang_x(), target);
  }

  // double ang_y = 12;
  if (this->ang_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(12, this->ang_y(), target);
  }

  // double ang_z = 13;
  if (this->ang_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(13, this->ang_z(), target);
  }

  // uint64 timestamp = 14;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(14, this->timestamp(), target);
  }

  // bool success = 15;
  if (this->success() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(15, this->success(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreX.rpc.OdometryResponse)
  return target;
}

size_t OdometryResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreX.rpc.OdometryResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double pos_x = 1;
  if (this->pos_x() != 0) {
    total_size += 1 + 8;
  }

  // double pos_y = 2;
  if (this->pos_y() != 0) {
    total_size += 1 + 8;
  }

  // double pos_z = 3;
  if (this->pos_z() != 0) {
    total_size += 1 + 8;
  }

  // double orient_x = 4;
  if (this->orient_x() != 0) {
    total_size += 1 + 8;
  }

  // double orient_y = 5;
  if (this->orient_y() != 0) {
    total_size += 1 + 8;
  }

  // double orient_z = 6;
  if (this->orient_z() != 0) {
    total_size += 1 + 8;
  }

  // double orient_w = 7;
  if (this->orient_w() != 0) {
    total_size += 1 + 8;
  }

  // double vel_x = 8;
  if (this->vel_x() != 0) {
    total_size += 1 + 8;
  }

  // double vel_y = 9;
  if (this->vel_y() != 0) {
    total_size += 1 + 8;
  }

  // double vel_z = 10;
  if (this->vel_z() != 0) {
    total_size += 1 + 8;
  }

  // double ang_x = 11;
  if (this->ang_x() != 0) {
    total_size += 1 + 8;
  }

  // double ang_y = 12;
  if (this->ang_y() != 0) {
    total_size += 1 + 8;
  }

  // double ang_z = 13;
  if (this->ang_z() != 0) {
    total_size += 1 + 8;
  }

  // uint64 timestamp = 14;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  // bool success = 15;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OdometryResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CoreX.rpc.OdometryResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const OdometryResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OdometryResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CoreX.rpc.OdometryResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CoreX.rpc.OdometryResponse)
    MergeFrom(*source);
  }
}

void OdometryResponse::MergeFrom(const OdometryResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CoreX.rpc.OdometryResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pos_x() != 0) {
    set_pos_x(from.pos_x());
  }
  if (from.pos_y() != 0) {
    set_pos_y(from.pos_y());
  }
  if (from.pos_z() != 0) {
    set_pos_z(from.pos_z());
  }
  if (from.orient_x() != 0) {
    set_orient_x(from.orient_x());
  }
  if (from.orient_y() != 0) {
    set_orient_y(from.orient_y());
  }
  if (from.orient_z() != 0) {
    set_orient_z(from.orient_z());
  }
  if (from.orient_w() != 0) {
    set_orient_w(from.orient_w());
  }
  if (from.vel_x() != 0) {
    set_vel_x(from.vel_x());
  }
  if (from.vel_y() != 0) {
    set_vel_y(from.vel_y());
  }
  if (from.vel_z() != 0) {
    set_vel_z(from.vel_z());
  }
  if (from.ang_x() != 0) {
    set_ang_x(from.ang_x());
  }
  if (from.ang_y() != 0) {
    set_ang_y(from.ang_y());
  }
  if (from.ang_z() != 0) {
    set_ang_z(from.ang_z());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.success() != 0) {
    set_success(from.success());
  }
}

void OdometryResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CoreX.rpc.OdometryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OdometryResponse::CopyFrom(const OdometryResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreX.rpc.OdometryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OdometryResponse::IsInitialized() const {
  return true;
}

void OdometryResponse::Swap(OdometryResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OdometryResponse::InternalSwap(OdometryResponse* other) {
  using std::swap;
  swap(pos_x_, other->pos_x_);
  swap(pos_y_, other->pos_y_);
  swap(pos_z_, other->pos_z_);
  swap(orient_x_, other->orient_x_);
  swap(orient_y_, other->orient_y_);
  swap(orient_z_, other->orient_z_);
  swap(orient_w_, other->orient_w_);
  swap(vel_x_, other->vel_x_);
  swap(vel_y_, other->vel_y_);
  swap(vel_z_, other->vel_z_);
  swap(ang_x_, other->ang_x_);
  swap(ang_y_, other->ang_y_);
  swap(ang_z_, other->ang_z_);
  swap(timestamp_, other->timestamp_);
  swap(success_, other->success_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata OdometryResponse::GetMetadata() const {
  protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StatusRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StatusRequest::StatusRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_robot_5fservice_2eproto::scc_info_StatusRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CoreX.rpc.StatusRequest)
}
StatusRequest::StatusRequest(const StatusRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CoreX.rpc.StatusRequest)
}

void StatusRequest::SharedCtor() {
}

StatusRequest::~StatusRequest() {
  // @@protoc_insertion_point(destructor:CoreX.rpc.StatusRequest)
  SharedDtor();
}

void StatusRequest::SharedDtor() {
}

void StatusRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StatusRequest::descriptor() {
  ::protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StatusRequest& StatusRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_robot_5fservice_2eproto::scc_info_StatusRequest.base);
  return *internal_default_instance();
}


void StatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreX.rpc.StatusRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool StatusRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CoreX.rpc.StatusRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:CoreX.rpc.StatusRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CoreX.rpc.StatusRequest)
  return false;
#undef DO_
}

void StatusRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CoreX.rpc.StatusRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CoreX.rpc.StatusRequest)
}

::google::protobuf::uint8* StatusRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CoreX.rpc.StatusRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreX.rpc.StatusRequest)
  return target;
}

size_t StatusRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreX.rpc.StatusRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StatusRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CoreX.rpc.StatusRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const StatusRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StatusRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CoreX.rpc.StatusRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CoreX.rpc.StatusRequest)
    MergeFrom(*source);
  }
}

void StatusRequest::MergeFrom(const StatusRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CoreX.rpc.StatusRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void StatusRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CoreX.rpc.StatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StatusRequest::CopyFrom(const StatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreX.rpc.StatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatusRequest::IsInitialized() const {
  return true;
}

void StatusRequest::Swap(StatusRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StatusRequest::InternalSwap(StatusRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StatusRequest::GetMetadata() const {
  protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StatusResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StatusResponse::kBatteryVFieldNumber;
const int StatusResponse::kBatteryPctFieldNumber;
const int StatusResponse::kIsChargingFieldNumber;
const int StatusResponse::kEmergencyStopFieldNumber;
const int StatusResponse::kStatusMsgFieldNumber;
const int StatusResponse::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StatusResponse::StatusResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_robot_5fservice_2eproto::scc_info_StatusResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CoreX.rpc.StatusResponse)
}
StatusResponse::StatusResponse(const StatusResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status_msg().size() > 0) {
    status_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_msg_);
  }
  ::memcpy(&battery_v_, &from.battery_v_,
    static_cast<size_t>(reinterpret_cast<char*>(&emergency_stop_) -
    reinterpret_cast<char*>(&battery_v_)) + sizeof(emergency_stop_));
  // @@protoc_insertion_point(copy_constructor:CoreX.rpc.StatusResponse)
}

void StatusResponse::SharedCtor() {
  status_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&battery_v_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&emergency_stop_) -
      reinterpret_cast<char*>(&battery_v_)) + sizeof(emergency_stop_));
}

StatusResponse::~StatusResponse() {
  // @@protoc_insertion_point(destructor:CoreX.rpc.StatusResponse)
  SharedDtor();
}

void StatusResponse::SharedDtor() {
  status_msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StatusResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StatusResponse::descriptor() {
  ::protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StatusResponse& StatusResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_robot_5fservice_2eproto::scc_info_StatusResponse.base);
  return *internal_default_instance();
}


void StatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreX.rpc.StatusResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&battery_v_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&emergency_stop_) -
      reinterpret_cast<char*>(&battery_v_)) + sizeof(emergency_stop_));
  _internal_metadata_.Clear();
}

bool StatusResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CoreX.rpc.StatusResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double battery_v = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &battery_v_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double battery_pct = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &battery_pct_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool is_charging = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_charging_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool emergency_stop = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &emergency_stop_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string status_msg = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status_msg().data(), static_cast<int>(this->status_msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CoreX.rpc.StatusResponse.status_msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CoreX.rpc.StatusResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CoreX.rpc.StatusResponse)
  return false;
#undef DO_
}

void StatusResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CoreX.rpc.StatusResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double battery_v = 1;
  if (this->battery_v() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->battery_v(), output);
  }

  // double battery_pct = 2;
  if (this->battery_pct() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->battery_pct(), output);
  }

  // bool is_charging = 3;
  if (this->is_charging() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->is_charging(), output);
  }

  // bool emergency_stop = 4;
  if (this->emergency_stop() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->emergency_stop(), output);
  }

  // string status_msg = 5;
  if (this->status_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status_msg().data(), static_cast<int>(this->status_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CoreX.rpc.StatusResponse.status_msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->status_msg(), output);
  }

  // uint64 timestamp = 6;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->timestamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CoreX.rpc.StatusResponse)
}

::google::protobuf::uint8* StatusResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CoreX.rpc.StatusResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double battery_v = 1;
  if (this->battery_v() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->battery_v(), target);
  }

  // double battery_pct = 2;
  if (this->battery_pct() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->battery_pct(), target);
  }

  // bool is_charging = 3;
  if (this->is_charging() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->is_charging(), target);
  }

  // bool emergency_stop = 4;
  if (this->emergency_stop() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->emergency_stop(), target);
  }

  // string status_msg = 5;
  if (this->status_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status_msg().data(), static_cast<int>(this->status_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CoreX.rpc.StatusResponse.status_msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->status_msg(), target);
  }

  // uint64 timestamp = 6;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->timestamp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreX.rpc.StatusResponse)
  return target;
}

size_t StatusResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreX.rpc.StatusResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string status_msg = 5;
  if (this->status_msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status_msg());
  }

  // double battery_v = 1;
  if (this->battery_v() != 0) {
    total_size += 1 + 8;
  }

  // double battery_pct = 2;
  if (this->battery_pct() != 0) {
    total_size += 1 + 8;
  }

  // uint64 timestamp = 6;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  // bool is_charging = 3;
  if (this->is_charging() != 0) {
    total_size += 1 + 1;
  }

  // bool emergency_stop = 4;
  if (this->emergency_stop() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StatusResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CoreX.rpc.StatusResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const StatusResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StatusResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CoreX.rpc.StatusResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CoreX.rpc.StatusResponse)
    MergeFrom(*source);
  }
}

void StatusResponse::MergeFrom(const StatusResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CoreX.rpc.StatusResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status_msg().size() > 0) {

    status_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_msg_);
  }
  if (from.battery_v() != 0) {
    set_battery_v(from.battery_v());
  }
  if (from.battery_pct() != 0) {
    set_battery_pct(from.battery_pct());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.is_charging() != 0) {
    set_is_charging(from.is_charging());
  }
  if (from.emergency_stop() != 0) {
    set_emergency_stop(from.emergency_stop());
  }
}

void StatusResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CoreX.rpc.StatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StatusResponse::CopyFrom(const StatusResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreX.rpc.StatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatusResponse::IsInitialized() const {
  return true;
}

void StatusResponse::Swap(StatusResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StatusResponse::InternalSwap(StatusResponse* other) {
  using std::swap;
  status_msg_.Swap(&other->status_msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(battery_v_, other->battery_v_);
  swap(battery_pct_, other->battery_pct_);
  swap(timestamp_, other->timestamp_);
  swap(is_charging_, other->is_charging_);
  swap(emergency_stop_, other->emergency_stop_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StatusResponse::GetMetadata() const {
  protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void VelocityCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VelocityCommand::kLinearXFieldNumber;
const int VelocityCommand::kLinearYFieldNumber;
const int VelocityCommand::kLinearZFieldNumber;
const int VelocityCommand::kAngularXFieldNumber;
const int VelocityCommand::kAngularYFieldNumber;
const int VelocityCommand::kAngularZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VelocityCommand::VelocityCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_robot_5fservice_2eproto::scc_info_VelocityCommand.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CoreX.rpc.VelocityCommand)
}
VelocityCommand::VelocityCommand(const VelocityCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&linear_x_, &from.linear_x_,
    static_cast<size_t>(reinterpret_cast<char*>(&angular_z_) -
    reinterpret_cast<char*>(&linear_x_)) + sizeof(angular_z_));
  // @@protoc_insertion_point(copy_constructor:CoreX.rpc.VelocityCommand)
}

void VelocityCommand::SharedCtor() {
  ::memset(&linear_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&angular_z_) -
      reinterpret_cast<char*>(&linear_x_)) + sizeof(angular_z_));
}

VelocityCommand::~VelocityCommand() {
  // @@protoc_insertion_point(destructor:CoreX.rpc.VelocityCommand)
  SharedDtor();
}

void VelocityCommand::SharedDtor() {
}

void VelocityCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VelocityCommand::descriptor() {
  ::protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VelocityCommand& VelocityCommand::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_robot_5fservice_2eproto::scc_info_VelocityCommand.base);
  return *internal_default_instance();
}


void VelocityCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreX.rpc.VelocityCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&linear_x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&angular_z_) -
      reinterpret_cast<char*>(&linear_x_)) + sizeof(angular_z_));
  _internal_metadata_.Clear();
}

bool VelocityCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CoreX.rpc.VelocityCommand)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double linear_x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &linear_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double linear_y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &linear_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double linear_z = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &linear_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double angular_x = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &angular_x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double angular_y = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &angular_y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double angular_z = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &angular_z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CoreX.rpc.VelocityCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CoreX.rpc.VelocityCommand)
  return false;
#undef DO_
}

void VelocityCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CoreX.rpc.VelocityCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double linear_x = 1;
  if (this->linear_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->linear_x(), output);
  }

  // double linear_y = 2;
  if (this->linear_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->linear_y(), output);
  }

  // double linear_z = 3;
  if (this->linear_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->linear_z(), output);
  }

  // double angular_x = 4;
  if (this->angular_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->angular_x(), output);
  }

  // double angular_y = 5;
  if (this->angular_y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->angular_y(), output);
  }

  // double angular_z = 6;
  if (this->angular_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->angular_z(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CoreX.rpc.VelocityCommand)
}

::google::protobuf::uint8* VelocityCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CoreX.rpc.VelocityCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double linear_x = 1;
  if (this->linear_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->linear_x(), target);
  }

  // double linear_y = 2;
  if (this->linear_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->linear_y(), target);
  }

  // double linear_z = 3;
  if (this->linear_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->linear_z(), target);
  }

  // double angular_x = 4;
  if (this->angular_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->angular_x(), target);
  }

  // double angular_y = 5;
  if (this->angular_y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->angular_y(), target);
  }

  // double angular_z = 6;
  if (this->angular_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->angular_z(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreX.rpc.VelocityCommand)
  return target;
}

size_t VelocityCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreX.rpc.VelocityCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double linear_x = 1;
  if (this->linear_x() != 0) {
    total_size += 1 + 8;
  }

  // double linear_y = 2;
  if (this->linear_y() != 0) {
    total_size += 1 + 8;
  }

  // double linear_z = 3;
  if (this->linear_z() != 0) {
    total_size += 1 + 8;
  }

  // double angular_x = 4;
  if (this->angular_x() != 0) {
    total_size += 1 + 8;
  }

  // double angular_y = 5;
  if (this->angular_y() != 0) {
    total_size += 1 + 8;
  }

  // double angular_z = 6;
  if (this->angular_z() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VelocityCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CoreX.rpc.VelocityCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const VelocityCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VelocityCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CoreX.rpc.VelocityCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CoreX.rpc.VelocityCommand)
    MergeFrom(*source);
  }
}

void VelocityCommand::MergeFrom(const VelocityCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CoreX.rpc.VelocityCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.linear_x() != 0) {
    set_linear_x(from.linear_x());
  }
  if (from.linear_y() != 0) {
    set_linear_y(from.linear_y());
  }
  if (from.linear_z() != 0) {
    set_linear_z(from.linear_z());
  }
  if (from.angular_x() != 0) {
    set_angular_x(from.angular_x());
  }
  if (from.angular_y() != 0) {
    set_angular_y(from.angular_y());
  }
  if (from.angular_z() != 0) {
    set_angular_z(from.angular_z());
  }
}

void VelocityCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CoreX.rpc.VelocityCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VelocityCommand::CopyFrom(const VelocityCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreX.rpc.VelocityCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VelocityCommand::IsInitialized() const {
  return true;
}

void VelocityCommand::Swap(VelocityCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VelocityCommand::InternalSwap(VelocityCommand* other) {
  using std::swap;
  swap(linear_x_, other->linear_x_);
  swap(linear_y_, other->linear_y_);
  swap(linear_z_, other->linear_z_);
  swap(angular_x_, other->angular_x_);
  swap(angular_y_, other->angular_y_);
  swap(angular_z_, other->angular_z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VelocityCommand::GetMetadata() const {
  protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ControlResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ControlResponse::kSuccessFieldNumber;
const int ControlResponse::kErrorMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ControlResponse::ControlResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_robot_5fservice_2eproto::scc_info_ControlResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CoreX.rpc.ControlResponse)
}
ControlResponse::ControlResponse(const ControlResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.error_msg().size() > 0) {
    error_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_msg_);
  }
  success_ = from.success_;
  // @@protoc_insertion_point(copy_constructor:CoreX.rpc.ControlResponse)
}

void ControlResponse::SharedCtor() {
  error_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  success_ = false;
}

ControlResponse::~ControlResponse() {
  // @@protoc_insertion_point(destructor:CoreX.rpc.ControlResponse)
  SharedDtor();
}

void ControlResponse::SharedDtor() {
  error_msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ControlResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ControlResponse::descriptor() {
  ::protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ControlResponse& ControlResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_robot_5fservice_2eproto::scc_info_ControlResponse.base);
  return *internal_default_instance();
}


void ControlResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreX.rpc.ControlResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  success_ = false;
  _internal_metadata_.Clear();
}

bool ControlResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CoreX.rpc.ControlResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool success = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &success_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string error_msg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_error_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->error_msg().data(), static_cast<int>(this->error_msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CoreX.rpc.ControlResponse.error_msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CoreX.rpc.ControlResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CoreX.rpc.ControlResponse)
  return false;
#undef DO_
}

void ControlResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CoreX.rpc.ControlResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->success(), output);
  }

  // string error_msg = 2;
  if (this->error_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_msg().data(), static_cast<int>(this->error_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CoreX.rpc.ControlResponse.error_msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->error_msg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CoreX.rpc.ControlResponse)
}

::google::protobuf::uint8* ControlResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CoreX.rpc.ControlResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->success(), target);
  }

  // string error_msg = 2;
  if (this->error_msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_msg().data(), static_cast<int>(this->error_msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CoreX.rpc.ControlResponse.error_msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->error_msg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreX.rpc.ControlResponse)
  return target;
}

size_t ControlResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreX.rpc.ControlResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string error_msg = 2;
  if (this->error_msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->error_msg());
  }

  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ControlResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CoreX.rpc.ControlResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ControlResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ControlResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CoreX.rpc.ControlResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CoreX.rpc.ControlResponse)
    MergeFrom(*source);
  }
}

void ControlResponse::MergeFrom(const ControlResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CoreX.rpc.ControlResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.error_msg().size() > 0) {

    error_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_msg_);
  }
  if (from.success() != 0) {
    set_success(from.success());
  }
}

void ControlResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CoreX.rpc.ControlResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ControlResponse::CopyFrom(const ControlResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreX.rpc.ControlResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ControlResponse::IsInitialized() const {
  return true;
}

void ControlResponse::Swap(ControlResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ControlResponse::InternalSwap(ControlResponse* other) {
  using std::swap;
  error_msg_.Swap(&other->error_msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(success_, other->success_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ControlResponse::GetMetadata() const {
  protobuf_robot_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_robot_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc
}  // namespace CoreX
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CoreX::rpc::OdometryRequest* Arena::CreateMaybeMessage< ::CoreX::rpc::OdometryRequest >(Arena* arena) {
  return Arena::CreateInternal< ::CoreX::rpc::OdometryRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CoreX::rpc::OdometryResponse* Arena::CreateMaybeMessage< ::CoreX::rpc::OdometryResponse >(Arena* arena) {
  return Arena::CreateInternal< ::CoreX::rpc::OdometryResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CoreX::rpc::StatusRequest* Arena::CreateMaybeMessage< ::CoreX::rpc::StatusRequest >(Arena* arena) {
  return Arena::CreateInternal< ::CoreX::rpc::StatusRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CoreX::rpc::StatusResponse* Arena::CreateMaybeMessage< ::CoreX::rpc::StatusResponse >(Arena* arena) {
  return Arena::CreateInternal< ::CoreX::rpc::StatusResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CoreX::rpc::VelocityCommand* Arena::CreateMaybeMessage< ::CoreX::rpc::VelocityCommand >(Arena* arena) {
  return Arena::CreateInternal< ::CoreX::rpc::VelocityCommand >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CoreX::rpc::ControlResponse* Arena::CreateMaybeMessage< ::CoreX::rpc::ControlResponse >(Arena* arena) {
  return Arena::CreateInternal< ::CoreX::rpc::ControlResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
