// proto/rpc_message.proto
syntax = "proto3";

package CoreX.rpc;

enum MessageType {
    REQUEST  = 0;
    RESPONSE = 1;
    ERROR    = 2;
}

enum ErrorCode {
    NO_ERROR         = 0;
    WRONG_PROTO      = 1;
    NO_SERVICE       = 2;
    NO_METHOD        = 3;
    INVALID_REQUEST  = 4;
}

message RpcMessage {  //RpcMessage为CoreX::rpc::RpcMessage，基类为::google::protobuf::Message
    MessageType type            = 1;
    fixed64     id              = 2;   // 请求/响应对应 ID
    string      service         = 3;   // "MathService"
    string      method          = 4;   // "Add"
    bytes       payload         = 5;   // Request 或 Response 的序列化结果
    ErrorCode   error           = 6;   // 仅在 RESPONSE/ERROR 时使用
    uint64      client_send_ts  = 7;   // client send timestamp (us)
    uint64      server_recv_ts  = 8;   // server receive timestamp (us)
    uint64      server_send_ts  = 9;   // server send timestamp (us)
    string      robot_id        = 10;  // 目标机器人 ID（空=任意）
}
